name: Overlay QA

on:
  push:
    paths-ignore:
      - 'README.md'

jobs:
  repoman:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: hacking-gentoo/action-repoman@master
